spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  grpc:
    server:
      port: 9091
      reflection:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8081