version: '3.8'

services:
  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  product-db:
    image: postgres:16
    container_name: product-db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data

  coupon-db:
    image: postgres:16
    container_name: coupon-db
    environment:
      POSTGRES_DB: coupon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - coupon-db-data:/var/lib/postgresql/data

  payment-db:
    image: postgres:16
    container_name: payment-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data

volumes:
  user-db-data:
  product-db-data:
  coupon-db-data:
  payment-db-data: